### ISSUE TITLE
Only usable for nested schemas

### ISSUE THREAD

**Issue by cfey** [jdthorpe/mongoose-ajv-plugin#1]
Hi,

I create a JSON schema
```
{
  "id":         "User",
  "type":       "object",
  "properties": {
    "email": {
      "type": "string",
      "format": "email"
    },
    "first_name": {
      "type": "string"
    },
    "last_name": {
      "type": "string"
    }
  },
  "required":   [
    "email"
  ]
}
```

and I want to use this as a mongoose model.
But when I try this
```
const userSchema = new Schema({
    type: Schema.Types.Mixed,
    schema: userSchemaJSON,
});
```

I get this error `Error: `schema` may not be used as a schema pathname` - I think because `schema` is a reserved word from mongoose (http://mongoosejs.com/docs/api.html#schema_Schema.reserved)

---

So my question is: Can I create a full mongoose schema from a json schema with this lib?

**Comment by jdthorpe** [comment]
The [document validation](https://www.npmjs.com/package/mongoose-ajv-plugin#document-validation) portion of the readme covers how to use the mongoose-ajv-plugin to validate whole documents, not just nested schemas.  

In short, you'll need to create a Mongoose shema: 

    const userSchema = new Schema({
        type: Schema.Types.Mixed,
    });

Then add your AJV schema
 
    userSchema.plugin(ajv_plugin,{schema:my_JSON_schema}); // the JSON schema, above

and then instantiate the user model:

    var userModel = mongoose.model('User', userSchema);

**Comment by jdthorpe** [comment]
For what it's worth, in the lastest version, I switch the keyword for identifying ajv schema to "ajv-schema" (from "schema") which is compatible with root level document validation with less code.  See the new (and much simpler) [readme](https://github.com/jdthorpe/mongoose-ajv-plugin) for details
